import { Injectable } from '@angular/core';

export interface Semana {
  numero: number;
  fechaInicio: string;
  circuito: string;
  duracion: string;
}

export interface CocheClase {
  nombreClase: string;
  coches: string[];
}

export interface SerieOficial {
  nombre: string;
  categoria?: string;
  clase?: string;
  licencia?: string;
  tipo?: string;
  coches: CocheClase[] | string[]; // Soporta clases o un arreglo simple de nombres de coches
  calendario?: any[]; // (O tu interfaz de CalendarioItem)
  semanas?: any[];
}

@Injectable({
  providedIn: 'root',
})
export class Schedule {
  // Base de datos ampliada a las 12 Semanas Reales
  private temporadaActual: SerieOficial[] = [
    {
      nombre: 'BMW M2 Cup',
      categoria: 'Sports Car',
      clase: 'R',
      // Ya no usamos string[], usamos CocheClase[]
      coches: [{ nombreClase: 'Default', coches: ['BMW M2 Racing (G87)'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '12 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Oulton Park Circuit - International',
          duracion: '12 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Circuito de Navarra - Speed Circuit',
          duracion: '12 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Summit Point Raceway - Summit Point Raceway',
          duracion: '12 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Virginia International Raceway - North Course',
          duracion: '12 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Winton Motor Raceway - National Circuit',
          duracion: '12 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Tsukuba Circuit - 2000 Full',
          duracion: '12 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Charlotte Motor Speedway Roval 2025',
          duracion: '12 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Lime Rock Park - Grand Prix',
          duracion: '12 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '12 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Oulton Park Circuit - Fosters',
          duracion: '12 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Circuit de Lédenon',
          duracion: '12 mins',
        },
      ],
    },
    {
      nombre: 'Global Mazda MX-5 Cup by Fanatec',
      categoria: 'Sports Car',
      clase: 'R',
      coches: [{ nombreClase: 'Default', coches: ['Global Mazda MX-5 Cup'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '12 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Oulton Park Circuit - International',
          duracion: '12 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Circuito de Navarra - Speed Circuit',
          duracion: '12 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Summit Point Raceway - Summit Point Raceway',
          duracion: '12 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Virginia International Raceway - North Course',
          duracion: '12 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Winton Motor Raceway - National Circuit',
          duracion: '12 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Tsukuba Circuit - 2000 Full',
          duracion: '12 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Charlotte Motor Speedway Roval 2025',
          duracion: '12 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Lime Rock Park - Grand Prix',
          duracion: '12 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '12 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Oulton Park Circuit - Fosters',
          duracion: '12 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Circuit de Lédenon',
          duracion: '12 mins',
        },
      ],
    },
    {
      nombre: 'BMW M Power Challenge',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ['BMW M2 Racing (G87)'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Road Atlanta - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Circuit Zandvoort - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Circuit de Nevers Magny-Cours - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Red Bull Ring - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Qualcomm Circuit (Naval Base Coronado)',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Rudskogen Motorsenter',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Clio Cup',
      categoria: 'Sports Car',
      clase: 'D', // Mapeado desde Rookie 4.0 según telemetría
      coches: [{ nombreClase: 'Default', coches: ['Renault Clio'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Oulton Park Circuit - International',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Tsukuba Circuit - 2000 Full',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Snetterton Circuit - 100',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Watkins Glen International - Cup',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Donington Park Racing Circuit - National',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Virginia International Raceway - North Course',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Rudskogen Motorsenter',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Summit Point Raceway - Summit Point Raceway',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Winton Motor Raceway - National Circuit',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Ford Mustang Challenge by Skip Barber',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ['Ford Mustang GT4'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Boot',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Circuit des 24 Heures du Mans',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'WeatherTech Raceway at Laguna Seca',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Daytona International Speedway - Road Course',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Summit Point Raceway - Summit Point Raceway',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Road America - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Snetterton Circuit - 300',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Sebring International Raceway - International',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Road Atlanta - Full Course',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Global Sports Car Challenge by Fanatec',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ['Cadillac CTS-V Racecar', 'Kia Optima'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Summit Point Raceway - Summit Point Raceway',
          duracion: '25 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '25 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '5 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '25 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Autódromo Hermanos Rodríguez - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Watkins Glen International - Boot',
          duracion: '25 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Willow Springs International Raceway - Big Willow',
          duracion: '25 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Silverstone Circuit - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Autódromo José Carlos Pace - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Homestead Miami Speedway - Road Course B',
          duracion: '25 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Mount Panorama Circuit',
          duracion: '25 mins',
        },
      ],
    },
    {
      nombre: 'Legends Road Cup by Go Motorsports Shop',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ["Legends Ford '34 Coupe"] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Circuito de Navarra - Speed Circuit - Short',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Tsukuba Circuit - 1000 Chicane',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Donington Park Racing Circuit - National',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Okayama International Circuit - Short',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Road Atlanta - Short',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Snetterton Circuit - 300',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Oulton Park Circuit - Fosters w/Hislop',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Road America - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Charlotte Motor Speedway Infield Road Course',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Lime Rock Park - Chicanes',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Circuit de Lédenon',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Misano World Circuit Marco Simoncelli - Truck',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Mission R Challenge',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ['Porsche Mission R'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Charlotte Motor Speedway Roval No Chicanes',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Classic',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Fuji International Speedway - No Chicane',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Mount Panorama Circuit',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Long Beach Street Circuit',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Hockenheimring Baden-Württemberg - Outer',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Oulton Park Circuit - Intl w/no Chicanes',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: '[Legacy] Silverstone Circuit - 2008 - Historical Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Road America - Full Course',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'NASCAR Euro Series',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [{ nombreClase: 'Default', coches: ['EURO NASCAR V8GP'] }],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Brands Hatch Circuit - Indy',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Circuit Zolder - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Oulton Park Circuit - Island',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Donington Park Racing Circuit - National',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Hockenheimring Baden-Württemberg - National A',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Nürburgring Grand-Prix-Strecke - Sprintstrecke',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Red Bull Ring - National',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Silverstone Circuit - National',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Snetterton Circuit - 200',
          duracion: '20 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Circuit de Barcelona Catalunya - National',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'Nurburgring Endurance Championship',
      categoria: 'Sports Car',
      clase: 'D',
      coches: [
        {
          nombreClase: 'GT3 Class',
          coches: [
            'Mercedes-AMG GT3 2020',
            'Ferrari 296 GT3',
            'Aston Martin Vantage GT3 EVO',
            'BMW M4 GT3 EVO',
            'Lamborghini Huracán GT3 EVO',
            'Porsche 911 GT3 R (992)',
            'Ford Mustang GT3',
          ],
        },
        {
          nombreClase: 'GT4 Class',
          coches: [
            'Mercedes-AMG GT4',
            'BMW M4 G82 GT4 Evo',
            'Aston Martin Vantage GT4',
            'Porsche 718 Cayman GT4 Clubsport MR',
          ],
        },
        {
          nombreClase: 'TCR Class',
          coches: ['Hyundai Elantra N TCR', 'Audi RS3 LMS Gen2 TCR', 'Honda Civic Type R TCR'],
        },
        {
          nombreClase: 'Other',
          coches: ['BMW M2 Racing (G87)'],
        },
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-03-21',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-04-04',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-04-25',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-05-23',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-06-06',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-04',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '360 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-08-08',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-29',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-10-10',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-11-07',
          circuito: 'Nürburgring Combined - Gesamtstrecke VLN',
          duracion: '240 mins',
        },
      ],
    },
    {
      nombre: 'Production Car Challenge by Sim-Lab',
      clase: 'D',
      categoria: 'Sports Car',
      coches: ['BMW M2 Racing (G87)', 'Toyota GR86', 'Renault Clio', 'Global Mazda MX-5 Cup'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '25 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Qualcomm Circuit (Naval Base Coronado)',
          duracion: '25 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Circuit de Spa-Francorchamps - Endurance',
          duracion: '25 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '25 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Road America - Full Course',
          duracion: '25 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'World Wide Technology Raceway (Gateway) - Road Course',
          duracion: '25 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Long Beach Street Circuit',
          duracion: '25 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Lime Rock Park - Classic',
          duracion: '25 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '25 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Daytona International Speedway - Road Course',
          duracion: '25 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Charlotte Motor Speedway - Roval No Chicanes',
          duracion: '25 mins',
        },
      ],
    },
    {
      nombre: 'Production Endurance Challenge',
      clase: 'D',
      categoria: 'Sports Car',
      coches: ['BMW M2 Racing (G87)', 'Toyota GR86', 'Renault Clio', 'Global Mazda MX-5 Cup'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-19',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '120 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-26',
          circuito: 'Qualcomm Circuit (Naval Base Coronado)',
          duracion: '120 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-07-03',
          circuito: 'Circuit de Spa-Francorchamps - Endurance',
          duracion: '120 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-10',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '120 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-17',
          circuito: 'Road America - Full Course',
          duracion: '120 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-24',
          circuito: 'World Wide Technology Raceway (Gateway) - Road Course',
          duracion: '120 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-31',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '120 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-07',
          circuito: 'Long Beach Street Circuit',
          duracion: '120 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-14',
          circuito: 'Lime Rock Park - Classic',
          duracion: '120 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-21',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '120 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-28',
          circuito: 'Daytona International Speedway - Road Course',
          duracion: '120 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-04',
          circuito: 'Charlotte Motor Speedway Roval No Chicanes',
          duracion: '120 mins',
        },
      ],
    },
    {
      nombre: 'Rain Master Challenge by Podium 1',
      clase: 'D',
      categoria: 'Sports Car',
      coches: [
        'Mercedes-AMG GT3 2020',
        'McLaren 720S GT3 EVO',
        'Ferrari 296 GT3',
        'Aston Martin Vantage GT3 EVO',
        'Audi R8 LMS EVO II GT3',
        'Acura NSX GT3 EVO 22',
        'BMW M4 GT3 EVO',
        'Lamborghini Huracán GT3 EVO',
        'Chevrolet Corvette Z06 GT3.R',
        'Porsche 911 GT3 R (992)',
        'Ford Mustang GT3',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Adelaide Street Circuit',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Miami International Autodrome - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Oran Park Raceway Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Red Bull Ring - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Circuit Zandvoort - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'MotorLand Aragón - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Road Atlanta - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Spec Racer Ford Challenge',
      clase: 'D',
      categoria: 'Sports Car',
      coches: ['SCCA Spec Racer Ford'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Road Atlanta Full Course',
          duracion: '16 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Circuit de Lédenon',
          duracion: '16 laps',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Autodromo Internazionale del Mugello - Short',
          duracion: '24 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Nürburgring Grand-Prix-Strecke - Grand Prix w/out Arena',
          duracion: '12 laps',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Oulton Park Circuit - Fosters',
          duracion: '23 laps',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Circuit of the Americas - Grand Prix',
          duracion: '10 laps',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Autodromo Nazionale Monza - Grand Prix.',
          duracion: '11 laps',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Misano World Circuit Marco Simoncelli - Grand Prix',
          duracion: '14 laps',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Oran Park Raceway - South',
          duracion: '33 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Indianapolis Motor Speedway - Road Course',
          duracion: '15 laps',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Mobility Resort Motegi - Grand Prix',
          duracion: '11 laps',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Tsukuba Circuit - 2000 Moto',
          duracion: '24 laps',
        },
      ],
    },
    {
      nombre: 'TCR Virtual Challenge',
      clase: 'D',
      categoria: 'Sports Car',
      coches: [
        'Hyundai Elantra N TCR',
        'Audi RS3 LMS Gen2 TCR',
        'Honda Civic Type R TCR',
        'Hyundai Veloster N TCR',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Oulton Park Circuit - International',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Boot',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Road Atlanta - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Nürburgring Grand-Prix-Strecke - BES/WEC',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Road America - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Brands Hatch Circuit - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'TCR Virtual Challenge - Fixed',
      clase: 'D',
      categoria: 'Sports Car',
      coches: [
        'Hyundai Elantra N TCR',
        'Audi RS3 LMS Gen2 TCR',
        'Honda Civic Type R TCR',
        'Hyundai Veloster N TCR',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Oulton Park Circuit - International',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Boot',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Road Atlanta - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Nürburgring Grand-Prix-Strecke - BES/WEC',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Road America - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Brands Hatch Circuit - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'Toyota GR86 Cup by SIMAGIC',
      clase: 'D',
      categoria: 'Sports Car',
      coches: ['Toyota GR86'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'WeatherTech Raceway at Laguna Seca-2026',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Circuit Zandvoort - Nationaal',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Summit Point Raceway - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Autódromo José Carlos Pace',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Mount Panorama Circuit',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Road America - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Virginia International Raceway - North Course',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'Advanced Mazda MX-5 Cup by Heusinkveld',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Global Mazda MX-5 Cup'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '5 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Oulton Park Circuit - Intl w/no Chicanes',
          duracion: '30 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Road Atlanta - Full Course',
          duracion: '30 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '30 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Nürburgring Grand-Prix-Strecke - BES/WEC',
          duracion: '30 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'WeatherTech Raceway at Laguna Seca - 2026',
          duracion: '30 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Qualcomm Circuit (Naval Base Coronado)',
          duracion: '30 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Silverstone Circuit - Grand Prix',
          duracion: '30 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari Moto',
          duracion: '30 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '30 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Circuit Gilles Villeneuve',
          duracion: '30 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Fuji International Speedway - Grand Prix',
          duracion: '30 mins',
        },
      ],
    },
    {
      nombre: 'Creventic Endurance Series',
      clase: 'C',
      categoria: 'Sports Car',
      coches: [
        'Mercedes-AMG GT3 2020',
        'Ferrari 296 GT3',
        'Aston Martin Vantage GT3 EVO',
        'Audi R8 LMS EVO II GT3',
        'BMW M4 GT3 EVO',
        'Lamborghini Huracán GT3 EVO',
        'Chevrolet Corvette Z06 GT3.R',
        'Porsche 911 GT3 R (992)',
        'Ford Mustang GT3',
        'Porsche 911 Cup (992.2)',
        'Ford Mustang GT4',
        'Mercedes-AMG GT4',
        'BMW M4 G82 GT4 Evo',
        'Aston Martin Vantage GT4',
        'Porsche 718 Cayman GT4 Clubsport MR',
        'McLaren 570S GT4',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-13',
          circuito: 'Autodromo Internazionale del Mugello - Grand Prix',
          duracion: '720 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-07-18',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '720 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-08-15',
          circuito: 'Circuit de Barcelona Catalunya - Grand Prix',
          duracion: '720 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-09-12',
          circuito: 'Nürburgring Grand-Prix-Strecke - Grand Prix',
          duracion: '720 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-09-26',
          circuito: 'Circuit de Barcelona Catalunya - Grand Prix',
          duracion: '1440 mins',
        },
      ],
    },
    {
      nombre: 'Ferrari 296 Challenge',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Ferrari 296 Challenge'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'WeatherTech Raceway at Laguna Seca - 2026',
          duracion: '15 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Oulton Park Circuit - International',
          duracion: '15 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Mount Panorama Circuit',
          duracion: '15 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Charlotte Motor Speedway - Roval No Chicanes',
          duracion: '15 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Algarve International Circuit - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Brands Hatch Circuit - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '15 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Motorsport Arena Oschersleben - B Course',
          duracion: '15 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Adelaide Street Circuit',
          duracion: '15 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Autodromo Nazionale Monza - Grand Prix',
          duracion: '15 mins',
        },
      ],
    },
    {
      nombre: 'GT Endurance Series by Simucube',
      clase: 'C',
      categoria: 'Sports Car',
      coches: [
        'Mercedes-AMG GT3 2020',
        'McLaren 720S GT3 EVO',
        'Ferrari 296 GT3',
        'Aston Martin Vantage GT3 EVO',
        'Audi R8 LMS EVO II GT3',
        'Acura NSX GT3 EVO 22',
        'BMW M4 GT3 EVO',
        'Lamborghini Huracán GT3 EVO',
        'Chevrolet Corvette Z06 GT3.R',
        'Porsche 911 GT3 R (992)',
        'Ford Mustang GT3',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-20',
          circuito: 'Watkins Glen International - Boot',
          duracion: '180 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-27',
          circuito: 'Oran Park Raceway - Grand Prix',
          duracion: '180 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-07-04',
          circuito: 'Mount Panorama Circuit',
          duracion: '180 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-11',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '180 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '180 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-25',
          circuito: 'Adelaide Street Circuit',
          duracion: '180 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-08-01',
          circuito: 'Hockenheimring Baden-Württemberg - Grand Prix',
          duracion: '180 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-08',
          circuito: 'Circuit des 24 Heures du Mans - 24 Heures du Mans',
          duracion: '180 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-15',
          circuito: 'Indianapolis Motor Speedway - Road Course',
          duracion: '180 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-22',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '180 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-29',
          circuito: 'Red Bull Ring - Grand Prix',
          duracion: '180 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-05',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '180 mins',
        },
      ],
    },
    {
      nombre: 'GT4 Falken Tyre Challenge',
      clase: 'C',
      categoria: 'Sports Car',
      coches: [
        'Ford Mustang GT4',
        'Mercedes-AMG GT4',
        'BMW M4 G82 GT4 Evo',
        'Aston Martin Vantage GT4',
        'Porsche 718 Cayman GT4 Clubsport MR',
        'McLaren 570S GT4',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Circuit des 24 Heures du Mans - 24 Heures du Mans',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Boot',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Autodromo Internazionale del Mugello - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Shell V-Power Motorsport Park at The Bend - International Circuit',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Road America - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Phillip Island Circuit',
          duracion: '20 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'IMSA Michelin Pilot Challenge',
      clase: 'C',
      categoria: 'Sports Car',
      coches: [
        'Ford Mustang GT4',
        'Mercedes-AMG GT4',
        'BMW M4 G82 GT4 Evo',
        'Aston Martin Vantage GT4',
        'Porsche 718 Cayman GT4 Clubsport MR',
        'McLaren 570S GT4',
        'Hyundai Elantra N TCR',
        'Audi RS3 LMS Gen2 TCR',
        'Honda Civic Type R TCR',
        'Hyundai Veloster N TCR',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-27',
          circuito: 'Watkins Glen International - Boot',
          duracion: '120 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-07-11',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '120 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-07-25',
          circuito: 'Road America - Full Course',
          duracion: '120 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-08-08',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '120 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-08-22',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '120 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-09-05',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '120 mins',
        },
      ],
    },
    {
      nombre: 'IMSA Sportscar Endurance Challenge',
      clase: 'C',
      categoria: 'Sports Car',
      coches: [
        'Ligier JS P320',
        'Ford Mustang GT4',
        'Mercedes-AMG GT4',
        'BMW M4 G82 GT4 Evo',
        'Aston Martin Vantage GT4',
        'Porsche 718 Cayman GT4 Clubsport MR',
        'McLaren 570S GT4',
      ],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-20',
          circuito: 'Circuit des 24 Heures du Mans 24 Heures du Mans',
          duracion: '120 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-07-04',
          circuito: 'Autodromo Internazionale del Mugello - Grand Prix',
          duracion: '120 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-07-18',
          circuito: 'Shell V-Power Motorsport Park at The Bend - International Circuit',
          duracion: '120 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-08-01',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '120 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-08-15',
          circuito: 'Phillip Island Circuit',
          duracion: '120 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-08-29',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari Grand Prix',
          duracion: '120 mins',
        },
      ],
    },
    {
      nombre: 'IMSA Vintage Series',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Nissan GTP ZX-T', 'Audi 90 GTO'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Phillip Island Circuit',
          duracion: '40 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: '[Legacy] Silverstone Circuit - 2008 - Historical Grand Prix',
          duracion: '40 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '40 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Watkins Glen International - Classic Boot',
          duracion: '60 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Motorsport Arena Oschersleben - Grand Prix',
          duracion: '40 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Detroit Grand Prix at Belle Isle - Belle Isle',
          duracion: '40 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Tsukuba Circuit - 2000 Full',
          duracion: '40 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Nürburgring Grand-Prix-Strecke - BES/WEC',
          duracion: '40 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Mid-Ohio Sports Car Course - Full Course',
          duracion: '40 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Willow Springs International Raceway - Big Willow',
          duracion: '60 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Oulton Park Circuit - Intl w/no Chicanes',
          duracion: '40 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Portland International Raceway - No Chicane',
          duracion: '40 mins',
        },
      ],
    },
    {
      nombre: 'iRacing Porsche Cup - Fixed by CONSPIT',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Porsche 911 Cup (992.2)'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Fuji International Speedway - Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Mount Panorama Circuit',
          duracion: '13 laps',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '11 laps',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Watkins Glen International - Boot',
          duracion: '14 laps',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Circuit de Barcelona Catalunya - Grand Prix',
          duracion: '14 laps',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Miami International Autodrome - Grand Prix',
          duracion: '13 laps',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Hockenheimring Baden-Württemberg - Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Autódromo José Carlos Pace - Grand Prix',
          duracion: '16 laps',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Red Bull Ring - Grand Prix',
          duracion: '17 laps',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Autodromo Nazionale Monza - Grand Prix',
          duracion: '14 laps',
        },
      ],
    },
    {
      nombre: 'iRacing Porsche Cup by CONSPIT',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Porsche 911 Cup (992.2)'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '15 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Fuji International Speedway - Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Mount Panorama Circuit',
          duracion: '13 laps',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '11 laps',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Watkins Glen International - Boot',
          duracion: '14 laps',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Circuit de Barcelona Catalunya - Grand Prix',
          duracion: '14 laps',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Miami International Autodrome - Grand Prix',
          duracion: '13 laps',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Hockenheimring Baden-Württemberg - Grand Prix',
          duracion: '15 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Autódromo José Carlos Pace - Grand Prix',
          duracion: '16 laps',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Red Bull Ring - Grand Prix',
          duracion: '17 laps',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Autodromo Nazionale Monza - Grand Prix',
          duracion: '14 laps',
        },
      ],
    },
    {
      nombre: 'LMP3 Trophy',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Ligier JS P320'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Circuit des 24 Heures du Mans - 24 Heures du Mans',
          duracion: '20 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Watkins Glen International - Boot',
          duracion: '20 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Autodromo Internazionale del Mugello - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '20 mins',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Shell V-Power Motorsport Park at The Bend - International Circuit',
          duracion: '20 mins',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Road America - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'St. Petersburg Grand Prix - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Phillip Island Circuit',
          duracion: '20 mins',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Virginia International Raceway - Full Course',
          duracion: '20 mins',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
          duracion: '20 mins',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Okayama International Circuit - Full Course',
          duracion: '20 mins',
        },
      ],
    },
    {
      nombre: 'Porsche Esports Supercup Global Open Qualifiers',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Porsche 911 Cup (992.2)'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-05-13',
          circuito: 'Circuit de Spa-Francorchamps - Grand Prix Pits',
          duracion: '30 mins',
        },
        {
          numero: 2,
          fechaInicio: '2026-05-20',
          circuito: 'Sebring International Raceway - International',
          duracion: '30 mins',
        },
        {
          numero: 3,
          fechaInicio: '2026-05-27',
          circuito: 'Suzuka International Racing Course - Grand Prix',
          duracion: '30 mins',
        },
        {
          numero: 4,
          fechaInicio: '2026-06-03',
          circuito: 'Nürburgring Grand-Prix-Strecke - Grand Prix',
          duracion: '30 mins',
        },
      ],
    },
    {
      nombre: 'Radical Esports Cup',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Radical SR10'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Road America - Full Course',
          duracion: '12 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Nürburgring Grand-Prix-Strecke - BES/WEC',
          duracion: '14 laps',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Barber Motorsports Park',
          duracion: '19 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
          duracion: '16 laps',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Road Atlanta - Full Course',
          duracion: '20 laps',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Silverstone Circuit - Grand Prix',
          duracion: '13 laps',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Willow Springs International Raceway - Big Willow',
          duracion: '22 laps',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Lime Rock Park - Classic',
          duracion: '33 laps',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Circuit Zolder - Alternate',
          duracion: '19 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Phillip Island Circuit',
          duracion: '18 laps',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Canadian Tire Motorsports Park',
          duracion: '21 laps',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Autódromo José Carlos Pace - Grand Prix',
          duracion: '17 laps',
        },
      ],
    },
    {
      nombre: 'Ring Meister by LVRY',
      clase: 'C',
      categoria: 'Sports Car',
      coches: ['Varios (Rotación semanal)'],
      calendario: [
        {
          numero: 1,
          fechaInicio: '2026-06-16',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 2,
          fechaInicio: '2026-06-23',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 3,
          fechaInicio: '2026-06-30',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 4,
          fechaInicio: '2026-07-07',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 5,
          fechaInicio: '2026-07-14',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 6,
          fechaInicio: '2026-07-21',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 7,
          fechaInicio: '2026-07-28',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 8,
          fechaInicio: '2026-08-04',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 9,
          fechaInicio: '2026-08-11',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 10,
          fechaInicio: '2026-08-18',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 11,
          fechaInicio: '2026-08-25',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
        {
          numero: 12,
          fechaInicio: '2026-09-01',
          circuito: 'Nürburgring Nordschleife - Industriefahrten',
          duracion: '3 laps',
        },
      ],
    },
  ];

  getCalendarioCompleto(): SerieOficial[] {
    return this.temporadaActual;
  }
}
